[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[program:zerotier]
command=/usr/sbin/zerotier-one -p%(ENV_ZT_PORT)s
priority=10
autorestart=unexpected
startsecs=3
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:file-server]
command=/usr/local/bin/node /opt/planet/container/file-server.js
user=planet
priority=20
autorestart=unexpected
startsecs=2
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:ztncui]
command=/usr/local/bin/node /opt/ztncui/src/bin/www
directory=/opt/ztncui/src
user=planet
priority=30
autorestart=unexpected
startsecs=3
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[eventlistener:exit-on-fatal]
command=/opt/planet/container/supervisor-exit-on-fatal.sh
events=PROCESS_STATE_FATAL
buffer_size=10
priority=100
